server:
  port: 5001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git: # 远程哭的git地址
          uri: https://github.com/mylin95/microservice-cloud-config.git